version: '3.8'

services:
  backend:
    build: ./server/
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  frontend:
    build: ./client/
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - mynetwork
    depends_on:
      - backend

networks:
  mynetwork:
    driver: bridge
